#server config
server:
  port: 5001
  ssl:
    key-store: classpath:server.keystore
    key-alias: kms
    enabled: true
    key-store-password: 123456
    key-store-type: JKS
  servlet:
    context-path: /WeBASE-Node-Manager


#mybatis config
mybatis:
  typeAliasesPackage: com.webank.webase.node.mgr
  mapperLocations: classpath:mapper/*.xml


# database connection configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/webasenodemanager?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: "defaultAccount"
    password: "defaultPassword"

#log config
logging:
  config: classpath:log/log4j2.xml
  level:
    com.webank.webase.node.mgr: info

#constants
constant:
  ###http request
  isUseSecurity: true   # login's authorization
  authTokenMaxAge: 1800


